.install-dependencies:
  variables:
    PHP_MEMORY_LIMIT: "2048M"
  image:
    name: registry.ulbricht.casa/jinya-cms/jinya-cms-php-base-test-image:latest
    pull_policy: always
  before_script:
    - install-php-extensions pdo_pgsql
    - phive --no-progress install --trust-gpg-keys D615FEE32FD1702834DACC9C8AC0BAA79732DD42,D8406D0D82947747293778314AA394086372C20A,CA7C2C7A30C8E8E1274A847651C67305FFC2E5C0
    - composer install

stages:
  - lint
  - test

pint:
  extends:
    - .install-dependencies
  stage: lint
  script:
    - ./vendor/bin/pint --test

phpstan:
  extends:
    - .install-dependencies
  stage: lint
  script:
    - ./tools/phpstan --no-progress analyze ./src --memory-limit 1G

phpunit:
  stage: test
  extends:
    - .install-dependencies
  script:
    - sleep 30
    - ./tools/phpunit --no-progress --log-junit report.xml --configuration phpunit.xml --coverage-cobertura=coverage.cobertura.xml
  artifacts:
    when: always
    paths:
      - report.xml
    reports:
      junit:
        - report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.cobertura.xml
  needs:
    - pint
  variables:
    MYSQL_DATABASE: jinya
    MYSQL_PASSWORD: jinya
    MYSQL_ROOT_PASSWORD: jinya
    MYSQL_USER: jinya
    POSTGRES_PASSWORD: jinya
    POSTGRES_USER: jinya
    POSTGRES_DB: jinya
  services:
    - name: ${DATABASE_IMAGE}
      alias: database
  parallel:
    matrix:
      # MySQL testing
      - DATABASE_DSN: 'mysql:host=database;port=3306;dbname=jinya;user=jinya;password=jinya;'
        DATABASE_TYPE: 'mysql'
        DATABASE_IMAGE: '$CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/library/mysql:lts'
      - DATABASE_DSN: 'mysql:host=database;port=3306;dbname=jinya;user=jinya;password=jinya;'
        DATABASE_TYPE: 'mysql'
        DATABASE_IMAGE: '$CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/library/mysql:latest'
      # MariaDB testing
      - DATABASE_DSN: 'mysql:host=database;port=3306;dbname=jinya;user=jinya;password=jinya;'
        DATABASE_TYPE: 'mysql'
        DATABASE_IMAGE: '$CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/library/mariadb:lts'
      - DATABASE_DSN: 'mysql:host=database;port=3306;dbname=jinya;user=jinya;password=jinya;'
        DATABASE_TYPE: 'mysql'
        DATABASE_IMAGE: '$CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/library/mariadb:latest'
      # Postgres testing
      - DATABASE_DSN: 'pgsql:host=database;port=5432;dbname=jinya;user=jinya;password=jinya;'
        DATABASE_TYPE: 'pgsql'
        DATABASE_IMAGE: '$CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/library/postgres:14-alpine'
      - DATABASE_DSN: 'pgsql:host=database;port=5432;dbname=jinya;user=jinya;password=jinya;'
        DATABASE_TYPE: 'pgsql'
        DATABASE_IMAGE: '$CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/library/postgres:15-alpine'
      - DATABASE_DSN: 'pgsql:host=database;port=5432;dbname=jinya;user=jinya;password=jinya;'
        DATABASE_TYPE: 'pgsql'
        DATABASE_IMAGE: '$CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/library/postgres:16-alpine'
      - DATABASE_DSN: 'pgsql:host=database;port=5432;dbname=jinya;user=jinya;password=jinya;'
        DATABASE_TYPE: 'pgsql'
        DATABASE_IMAGE: '$CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/library/postgres:17-alpine'
      # Sqlite testing
      - DATABASE_DSN: 'sqlite::memory:'
        DATABASE_TYPE: 'sqlite'
        DATABASE_IMAGE: '$CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/library/alpine:latest'
