<?php

namespace Jinya\Router\Extensions\Database\Classes;

use DateTime;
use Jinya\Database\Attributes\Column;
use Jinya\Database\Attributes\Id;
use Jinya\Database\Entity;
use Jinya\Router\Extensions\Database\Attributes\Find;
use Jinya\Router\Http\FunctionMiddleware;

#[Find(middleware: new FunctionMiddleware('strtolower', []))]
class ApiTestEntityWithMiddleware extends Entity
{
    #[Id]
    #[Column(autogenerated: true)]
    public int $id;

    #[Column]
    public string $name;

    #[Column(sqlName: 'display_name')]
    public string $displayName;

    #[Column]
    public DateTime $date;

    public string $unused = '';
}
