<?php

namespace Jinya\Router\Extensions\Database\Classes;

use DateTime;
use Jinya\Database\Attributes\Column;
use Jinya\Database\Attributes\Id;
use Jinya\Database\Attributes\Table;
use Jinya\Database\Entity;
use JsonSerializable;

#[Table('referenced_test_entity')]
class ReferencedTestEntity extends Entity implements JsonSerializable
{
    #[Id]
    #[Column(autogenerated: true)]
    public int $id;

    #[Column]
    public string $name;

    #[Column(sqlName: 'display_name')]
    public string $displayName;

    #[Column]
    public DateTime $date;

    #[Column(sqlName: 'test_entity_id')]
    public int $testEntityId;

    public function jsonSerialize(): array
    {
        return [
            'id' => $this->id,
            'name' => $this->name,
            'displayName' => $this->displayName,
            'date' => $this->date->format(DATE_ATOM),
            'testEntityId' => $this->testEntityId,
        ];
    }
}
