<?php

namespace Jinya\Router\Extensions\Database\Classes;

use DateTime;
use Jinya\Database\Attributes\Column;
use Jinya\Database\Attributes\Id;
use Jinya\Database\Attributes\Table;
use Jinya\Database\Entity;

#[Table('test_entity')]
class TestEntity extends Entity
{
    #[Id]
    #[Column(autogenerated: true)]
    public int $id;

    #[Column]
    public string $name;

    #[Column(sqlName: 'display_name')]
    public string $displayName;

    #[Column]
    public DateTime $date;
}
