<?php

namespace Jinya\Router\Extensions;

class JinyaDatabaseExtension extends Extension
{
    public function additionalRoutes(): string
    {
        return parent::additionalRoutes(); // TODO: Change the autogenerated stub
    }

}
